name: PR Merged Workflow

on:
  pull_request:
    types: [closed]

jobs:
  check_merge:
    runs-on: ubuntu-latest

    steps:
      - name: VÃ©rifier si la PR a Ã©tÃ© mergÃ©e
        if: github.event.pull_request.merged == true
        run: echo "ğŸ‰ La Pull Request a Ã©tÃ© mergÃ©e avec succÃ¨s !"
